src/carts/urls.py
from django.urls import path

from . import views
app_name='cart'

urlpatterns = [
    path('add-to-cart/', views.UpdateCart.as_view(), name='add-to-cart'),
    path('recalculate-cart/', views.ReсalculateCart.as_view(), name='recalculate-cart'),
]

src/orders/urls.py
from django.urls import path

from . import views

app_name = 'order'

urlpatterns = [
    path('history/', views.UserOrder.as_view(), name = 'history'),
    path('checkout/<int:cart_pk>/', views.OrderConfirm.as_view(), name='checkout'),
    path('list/', views.OrderList.as_view(), name = 'list'),
    path('update/<int:pk>/', views.OrderUpdate.as_view(), name = 'update'),
    path('detail/<int:pk>/', views.OrderDetail.as_view(), name = 'detail'),
    path('success/<int:pk>/', views.OrderSuccess.as_view(), name = 'success'),

    
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from books import views as bookviews
from dictionaries import urls as dictionaries_urls 
from books import urls as books_urls
from accounts import urls as accounts_urls
from carts import urls as carts_urls
from orders import urls as orders_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', bookviews.HomePage.as_view(), name='home-page'),  
    path('dictionaries/', include(dictionaries_urls)),
    path('accounts/', include(accounts_urls)),
    path('book/', include(books_urls)),
    path('cart/', include(carts_urls, namespace='cart')),
    path('order/', include(orders_urls, namespace='order'))   
] 

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/starter-template/">

    <!-- Bootstrap core CSS -->
{% comment %} <link href="{% static 'dictionaries/css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"> {% endcomment %}
<link href="{% static 'dictionaries/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/4.5/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">

<link rel="mask-icon" href="/docs/4.5/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon.ico">
<meta name="msapplication-config" content="/docs/4.5/assets/img/favicons/browserconfig.xml">
<meta name="theme-color" content="#563d7c">


    <style>
    body {
    padding-top: 5rem;
    }
    .starter-template {
    padding: 1rem 1.5rem;
    text-align: center;
    }
    #card-body{
    position:relative;
    height:185px;
    }
    a {
    color: $gray-900;
    hover:  $gray-900;
    class: text-body;
    }
    #book-name{
    height:70px;
    overflow: hidden;
    -webkit-line-clamp:3;
    display:  -webkit-box;
    -webkit-box-orient: vertical;
    }
    #btn-group{
    position:absolute; 
	  bottom:10px;
    }
    i {
    font-size: 20px;
    }

    #i-cart-list {
    font-size: 25px;
    }
    .fas {
    font-size: 12px; 
    }
    #pencil, #cart{
    font-size: 12px; 
    color: #007474
    }
    #star-grey{
    color:grey
    }
    .fa-star {
    color: gold;
    font-size: 12px; 
    }
    .fa-check-circle{
    color: #77c346;
    font-size: 80px; 
    }
    .table-success{
    background-color: #cae8b6;
    }
    table.table.table-borderless:{
    padding: 1rem
    }
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color: #007474;">

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home-page' %}">Главная<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'book-list' %}">Каталог<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'cart:add-to-cart' %}?book={{book.pk}}">Корзина<span class="sr-only">(current)</span></a>
      </li>
      {% if user.is_staff %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'order:list' %}">Заказы<span class="sr-only">(current)</span></a>
      </li>
      {% endif %}
      {% if user.is_staff %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-white" href="#" id="dropdown01"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Словари</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="{% url 'author-list' %}"> Авторы</a>
          <a class="dropdown-item"  href="{% url 'genre-list' %}">Жанры</a>
          <a class="dropdown-item" href="{% url 'publisher-list' %}">Издательства</a>
          <a class="dropdown-item"  href="{% url 'book-series-list' %}">Серии книг  </a>
        </div>
      </li>
      {% endif %}
    </ul>
    <ul class="navbar-nav col-auto">
    {% if user.is_authenticated %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-white" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{user}}</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="{% url 'user-update' %}">Мой профиль</a>
          <a class="dropdown-item" href="{% url 'user-profile-update'%}">Контактная информация</a>
          <hr class="dropdown-divider">
          <a class="dropdown-item" href="{% url 'order:history' %}">История заказов</a>
        </div>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'logout' %}">Выйти<span class="sr-only">(current)</span></a>
      </li>
    {% endif %}
    {% if user.is_anonymous %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'login' %}">Войти<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'register' %}">Регистрация<span class="sr-only">(current)</span></a>
      </li>
    {% endif %}
    </ul>

  </div>
</nav>

<main role="main" class="container">
<div class="starter-template">
</div>
{% block main_content %}{% endblock main_content  %}
<div class="starter-template">
</div>
</main><!-- /.container -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>

<script src="{% static 'dictionaries/js/bootstrap.bundle.min.js' %}" ></script></body>

</html>