src/carts/urls.py
from django.urls import path

from . import views
app_name='cart'

urlpatterns = [
    path('add-to-cart/', views.UpdateCart.as_view(), name='add-to-cart'),
    path('recalculate-cart/', views.ReсalculateCart.as_view(), name='recalculate-cart'),
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from books import views as bookviews
from dictionaries import urls as dictionaries_urls 
from books import urls as books_urls
from accounts import urls as accounts_urls
from carts import urls as carts_urls
from orders import urls as orders_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', bookviews.HomePage.as_view(), name='home-page'),  
    path('dictionaries/', include(dictionaries_urls)),
    path('accounts/', include(accounts_urls)),
    path('book/', include(books_urls)),
    path('cart/', include(carts_urls, namespace='cart')),
    path('order/', include(orders_urls, namespace='order'))   
] 

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/carts/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your views here.
User = get_user_model()

class Cart(models.Model):
    customer = models.ForeignKey(
        User,
        on_delete=models.PROTECT, 
        verbose_name="Корзина пользователя",
        related_name="cart",
        blank=False,
        null=True
    )
    def __str__(self):
        return f"Корзина {self.customer}"

    @property 
    def total_summ(self):
        all_books = self.books.all()
        total = 0
        for book in all_books:
            total += book.total_price
        return total

class BookInCart(models.Model):
    cart = models.ForeignKey(
        Cart, 
        verbose_name="Корзина пользователя",
        related_name="books", 
        on_delete=models.CASCADE)
    book = models.ForeignKey(
        "books.Book",
        on_delete=models.PROTECT,
        verbose_name="Товары в корзине" 
    )
    price = models.DecimalField(
        verbose_name="Цена, руб.",
        max_digits=5,
        decimal_places=2,
        blank=True, null=True)
        
    quantity = models.PositiveIntegerField(
        verbose_name = "Колечество товара",
        default = 1)
        
    def __str__(self):
        return f"{self.book} в корзине {self.cart}"

    @property
    def total_price(self):
        return self.book.price *self.quantity

src/carts/views.py
from django.shortcuts import render
from django.views.generic import DetailView, RedirectView, UpdateView
from . import models, utils 
from books import models as book_models
from django.contrib.auth import get_user_model
from django.urls import reverse
 
User = get_user_model()

class UpdateCart(DetailView):
    model = models.Cart
    template_name = "carts/add-to-cart.html"

    def get_object(self, *args, **kwargs):
        book_id = self.request.GET.get('book')
        if not book_id:
            current_cart_pk = self.request.session.get('current_cart_pk')
            if current_cart_pk:
                current_cart = models.Cart.objects.filter(pk=current_cart_pk).first()
                return current_cart or []
            return []
        else:
            current_cart_pk = self.request.session.get('current_cart_pk')
            current_customer=self.request.user
            if current_customer.is_anonymous:
                current_customer = None
            current_cart, cart_created = models.Cart.objects.get_or_create(
                pk = current_cart_pk,
                defaults = {'customer': current_customer}    
            )
            if cart_created:
                self.request.session['current_cart_pk'] = current_cart.pk
            book = book_models.Book.objects.get(pk=book_id)
            price = book.price
            book_in_cart, book_created = models.BookInCart.objects.get_or_create(
                cart = current_cart,
                book = book,
                price = price,
                defaults = {'quantity': 1}
            )
            price = book_in_cart.price
            book_in_cart.save()
            if not book_created:
                book_in_cart.quantity += 1
                book_in_cart.save()
        return current_cart

class ReсalculateCart(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        current_cart_pk, cart_items = utils.harvest_data(self)
        current_cart_pk_for_url = self.request.session.get('current_cart_pk')
        return_urls = {
            'checkout': reverse('order:checkout', kwargs={'cart_pk': current_cart_pk_for_url})
        }
        if not current_cart_pk: 
            return reverse('cart:add-to-cart')
        action = utils.update_items_in_cart(cart_items, current_cart_pk)
        
        return return_urls.get(action, reverse('cart:add-to-cart'))

src/carts/templates/carts/add-to-cart.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title%} Корзина {% endblock title %}
{% block main_content %}
{% if object  %}
<h1>Корзина</h1>
<br>
<form action="{% url 'cart:recalculate-cart'%}" method="GET">
  <table class="table">
    <tbody>
  {% for book_in_cart in object.books.all %}
      <tr>
        <td><img  width="70" src="{{book_in_cart.book.book_picture.url}}" alt="{{book_in_cart.book.name}}"></td>
        <td>{{book_in_cart.book}}</td>
        <td>{{book_in_cart.price}} руб.</td>
        <td><input type='number' min=0 name="{{book_in_cart.pk}}" value={{book_in_cart.quantity}}> шт.</td>
        <td>{{book_in_cart.total_price}} руб.</td>
      </tr>
    {% endfor %}
      <tr>
        <td colspan=4><b>Итого:</b></td>
        <td><b>{{object.total_summ}} руб.</b></td>
      </tr>
    </tbody>
  </table>
<button type="submit" name="btn" value='recalculate' class='btn btn-success'>Рассчитать</button>
<button type="submit" name="btn" value='checkout' class='btn btn-warning'>Оформить заказ</button>
</form>
{% else %}
<h2>Ваша корзина пуста</h2><br>
<a href = "{% url 'book-list' %}" class='btn btn-success'>Перейти в каталог</a>
{% endif %}
{% endblock main_content  %}