src/carts/urls.py
from django.urls import path

from . import views
app_name='cart'

urlpatterns = [
    path('add-to-cart/', views.UpdateCart.as_view(), name='add-to-cart'),
    path('recalculate-cart/', views.ReсalculateCart.as_view(), name='recalculate-cart'),
]

src/orders/urls.py
from django.urls import path

from . import views

app_name = 'order'

urlpatterns = [
    path('history/', views.UserOrder.as_view(), name = 'history'),
    path('checkout/<int:cart_pk>/', views.OrderConfirm.as_view(), name='checkout'),
    path('list/', views.OrderList.as_view(), name = 'list'),
    path('update/<int:pk>/', views.OrderUpdate.as_view(), name = 'update'),
    path('detail/<int:pk>/', views.OrderDetail.as_view(), name = 'detail'),
    path('success/<int:pk>/', views.OrderSuccess.as_view(), name = 'success'),

    
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from books import views as bookviews
from dictionaries import urls as dictionaries_urls 
from books import urls as books_urls
from accounts import urls as accounts_urls
from carts import urls as carts_urls
from orders import urls as orders_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', bookviews.HomePage.as_view(), name='home-page'),  
    path('dictionaries/', include(dictionaries_urls)),
    path('accounts/', include(accounts_urls)),
    path('book/', include(books_urls)),
    path('cart/', include(carts_urls, namespace='cart')),
    path('order/', include(orders_urls, namespace='order'))   
] 

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/orders/models.py
from django.db import models
import datetime

# Create your models here.

class Order(models.Model):
    cart = models.OneToOneField(
        "carts.Cart",
        verbose_name = "Корзина пользователя",
        on_delete=models.PROTECT,
        related_name = 'orders'
    )

    address = models.TextField(
        verbose_name = "Адрес доставки")

    telephone_number = models.CharField(
        verbose_name="Контактный номер",
        max_length=15)
    
    customer_comments = models.TextField(
        verbose_name = "Комментарии к заказу",
        blank = True,
        null = True)
    
    created = models.DateTimeField(
        verbose_name="Дата заказа",
        auto_now_add=True,
        blank = True,
        null = True)
   
    open_order = 'Новый'
    processed_order = 'В обработке'
    closed_order = 'Закрыт'
    cancelled_order = 'Отменен'
    order_status_choices = [(open_order, "Новый"), (processed_order, "В обработке"), (closed_order, "Закрыт"), (cancelled_order, 'Отменен')]

    order_status = models.CharField(
        verbose_name="Статус заказа",
        choices = order_status_choices,
        default = open_order,
        max_length = 20) 

    # def __str__(self):
    #     return self.cart.customer
    

src/orders/forms.py
from django import forms
from django.db.models import fields
from . import models

class SearchForm(forms.Form):
    query = forms.CharField(label="")
    field = forms.CharField(widget=forms.HiddenInput)
    direction = forms.CharField(widget=forms.HiddenInput)

src/orders/views.py
from django.shortcuts import render
from django.views.generic import UpdateView, ListView, DetailView
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse_lazy
from django.db.models import Q
from carts import models as cart_models
from accounts import models as account_models
from django.contrib.auth.models import User
from . import forms


from . import models
# Create your views here.
class OrderConfirm(UpdateView):
    model=models.Order
    fields = ('address', 'telephone_number', 'customer_comments')
    def get_object(self, *args, **kwargs):
        current_cart_pk = self.request.session.get('current_cart_pk')
        if not current_cart_pk:
            pass
        else:
            current_cart = cart_models.Cart.objects.get(pk = current_cart_pk)
            current_order_pk = self.request.session.get('current_order_pk')
            current_customer = self.request.user 
            if current_customer.is_anonymous:
                current_customer_profile = None
            else:
                current_customer_profile = account_models.Profile.objects.filter(user = current_customer).first()
                if not current_customer_profile:
                    current_customer_profile = None
            if current_customer and current_customer_profile:
                user_default_data = {
                    'cart': current_cart,
                    'address': current_customer.profile.address,
                    'telephone_number': current_customer.profile.telephone
                }
            else:
                user_default_data = {
                    'cart': current_cart,
                    'address': "",
                    'telephone_number': ""
                } 
            current_order, order_created = models.Order.objects.get_or_create(
                pk = current_order_pk,
                defaults =  user_default_data   
            )
            if order_created:
                self.request.session['current_order_pk'] = current_order.pk
        return current_order

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_cart_pk = self.request.session.get('current_cart_pk')
        cart = cart_models.Cart.objects.get(pk=current_cart_pk)
        context["cart"] = cart
        return context

    def get_success_url(self):
        del self.request.session['current_cart_pk']
        del self.request.session['current_order_pk']
        return reverse_lazy('order:success', kwargs={'pk': self.object.pk})

class UserOrder(ListView):
    model = models.Order
    template_name = 'orders/order_user_history.html'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # current_customer = self.request.user 
        # customer_carts = cart_models.Cart.objects.filter(customer = current_customer)
        # user_orders = models.Order.objects.filter(cart__in = customer_carts)
        # context["user_orders"] = user_orders
        field_to_sort_on = self.request.GET.get('field')
        direction_to_sort_on = self.request.GET.get('direction')
        context["field_to_sort_on"] = field_to_sort_on
        context["direction_to_sort_on"] = direction_to_sort_on
        query = self.request.GET.get('query')
        context['search_form'] = forms.SearchForm(
            initial={
                'query': query,
                'field': field_to_sort_on,      
                'direction': direction_to_sort_on
            })
        print(field_to_sort_on, direction_to_sort_on)
        return context

    def get_queryset(self):
        current_customer = self.request.user 
        customer_carts = cart_models.Cart.objects.filter(customer = current_customer)
        user_orders = models.Order.objects.filter(cart__in = customer_carts)
        query_set = user_orders
        query = self.request.GET.get('query')
        if query:
            query_set = query_set.filter(pk__icontains=query)
        return query_set
    



    
class OrderList(PermissionRequiredMixin, ListView):
    queryset = models.Order.objects.all().order_by('pk')
    queryset = queryset.reverse()
    permission_required = ("orders.view_order", "orders.add_order", "orders.change_order")
    login_url=reverse_lazy('login')
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        field_to_sort_on = self.request.GET.get('field')
        direction_to_sort_on = self.request.GET.get('direction')
        context["field_to_sort_on"] = field_to_sort_on
        context["direction_to_sort_on"] = direction_to_sort_on
        query = self.request.GET.get('query')
        context['search_form'] = forms.SearchForm(
            initial={
                'query': query,
                'field': field_to_sort_on,      
                'direction': direction_to_sort_on
            })
        return context
    
    def get_ordering(self):
        ordering_by = 'pk'    
        field_to_sort_on = self.request.GET.get('field')
        direction_to_sort_on = self.request.GET.get('direction')
        direction = {'up': ""}
        if field_to_sort_on and direction_to_sort_on:
            ordering_by = f"{direction.get(direction_to_sort_on, '-')}{field_to_sort_on}"
        return ordering_by
    
    def get_queryset(self):
        query = self.request.GET.get('query')
        query_set = super().get_queryset()
        if query:
            # query_set = query_set.filter(address__icontains=query) 
            query_set = query_set.filter(Q(address__icontains=query)|Q(pk__icontains=query)) 

        return query_set

class OrderUpdate(PermissionRequiredMixin, UpdateView):
    model = models.Order
    fields = ('address', 'telephone_number', 'customer_comments', 'order_status')
    permission_required = ("orders.view_order", "orders.add_order", "orders.change_order")
    login_url=reverse_lazy('login')
    success_url=reverse_lazy('order:list')
    template_name = 'orders/order_update.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_order_pk = self.object.pk  
        current_order = models.Order.objects.get(pk=current_order_pk)
        cart = current_order.cart
        context["cart"] = cart
        return context
    
class OrderDetail(DetailView):
    model = models.Order

class OrderSuccess(DetailView):
    model = models.Order
    template_name='orders/order_success.html'

src/orders/templates/orders/order_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title%} Информация о заказе {% endblock title %}
{% block main_content %}
    <h1>Заказ # {{object.pk}}</h1>
    <table class="table table-success">
    <tr>
        <th>Создан</th>
        <th>Статус</th>
        <th>Номер телефона</th>
        <th>Адрес</th>
        <th>Комментарии</th>
    </tr>
    <tr>
        <td>{{object.created}}</td>
        <td>{{object.order_status}}</td>
        <td>{{object.telephone_number}}</td>
        <td>{{object.address}}</td>
        <td>{{object.customer_comments}}</td>
    </tr>
    </table>
    <table class='table'>
        {% for ordered_book in object.cart.books.all %}
        <tr>
            <td><img  width="70" src="{{ordered_book.book.book_picture.url}}" alt="{{ordered_book.book.name}}"></td>
            <td>{{ordered_book.book}}</td>
            <td>{{ordered_book.price}} руб.</td>
            <td>{{ordered_book.quantity}} шт.</td>
            <td>{{ordered_book.total_price}} руб.</td>
        </tr>
        {% endfor %}
        <tr>
        <td colspan=4><b>Итого:</b></td>
        <td><b>{{object.cart.total_summ}} руб.</b></td>
      </tr>
    </table> 

{% endblock main_content  %}

src/orders/templates/orders/order_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title%} Подтверждение заказа {% endblock title %}
{% block main_content %}
    <h1>Подтверждение заказа</h1><hr> 
    <h6>{{cart.customer.first_name|default:"Пожалуйста, укажите Ваше имя в поле <b>Комментарии к заказу</b>"}}</h6><hr>
    {% for book in cart.books.all %}{{book.book.name}} {{book.book.price}} руб. x{{book.quantity}}<br>{% endfor %}
    </p>   
    <h4>Итого: {{cart.total_summ}} руб. <a href="{% url 'cart:add-to-cart' %}"  class='btn btn-warning'>Вернуться к корзине</a></h4>
    <form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button align=center class="btn btn-success">Готово</button>
    </form>
{% endblock main_content  %}

src/orders/templates/orders/order_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title%} История заказов {% endblock title %}

{% block main_content %}
    <h2 class="row alert alert-warning">Заказы</h2> 
    <form action="" method="GET">
    {{search_form|crispy}}
    </form>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>   
<table class='table table-hover'>
<tr>
    <th><a class="link-success text-body" href="{% url 'order:list'%}?field=pk&direction={% if field_to_sort_on == 'pk' and direction_to_sort_on == 'up'  %}down{% else %}up{% endif %}">#
    {% if field_to_sort_on == 'pk' and direction_to_sort_on == 'up' %} <i class="fas fa-chevron-up"></i>
    {% elif field_to_sort_on == 'pk' and direction_to_sort_on == 'down' %} <i class="fas fa-chevron-down"></i>
    {% endif %}
    </a></th>
    <th><a class="link-success text-body" href="{% url 'order:list'%}?field=created&direction={% if field_to_sort_on == 'created' and direction_to_sort_on == 'up'  %}down{% else %}up{% endif %}">Дата
    {% if field_to_sort_on == 'created' and direction_to_sort_on == 'up' %} <i class="fas fa-chevron-up"></i>
    {% elif field_to_sort_on == 'created' and direction_to_sort_on == 'down' %} <i class="fas fa-chevron-down"></i>
    {% endif %}
    </a></th>
    <th><a class="link-success text-body"  href="{% url 'order:list'%}?field=order_status&direction={% if field_to_sort_on == 'order_status' and direction_to_sort_on == 'up'  %}down{% else %}up{% endif %}">Статус
    {% if field_to_sort_on == 'order_status' and direction_to_sort_on == 'up' %} <i class="fas fa-chevron-up"></i>
    {% elif field_to_sort_on == 'order_status' and direction_to_sort_on == 'down' %} <i class="fas fa-chevron-down"></i>
    {% endif %}
    </a></th>
    <th><a class="link-success text-body"  href="{% url 'order:list'%}?field=address&direction={% if field_to_sort_on == 'address' and direction_to_sort_on == 'up'  %}down{% else %}up{% endif %}">Адрес
    {% if field_to_sort_on == 'address' and direction_to_sort_on == 'up' %} <i class="fas fa-chevron-up"></i>
    {% elif field_to_sort_on == 'address' and direction_to_sort_on == 'down' %} <i class="fas fa-chevron-down"></i>
    {% endif %}
    </a></th>
    <th>Книги</th>
    <th>Итого,<br>руб.</th>
</tr>
    {% for order in order_list %}
    <tr>
        <td><a href = "{% url 'order:update'  order.pk  %}">{{order.pk}}</a></td>
        <td>{{order.created}}</td>
        <td>{{order.order_status}}</td>
        <td>{{order.address}}</td>
        <td>{% for book in order.cart.books.all %}{{book.book.name}} x{{book.quantity}}<br>{% endfor %}</td>
        <td>{{order.cart.total_summ}}</td>
    </tr>
        {% endfor %}
</table>
{% endblock main_content  %}

src/orders/templates/orders/order_success.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title%} Заказ создан {% endblock title %}
{% block main_content %}
<div> <h1><span class="align-middle"><i class="fad fa-check-circle"></i></span> Спасибо за заказ!</h1>
Ваш заказ принят оператором. Мы свяжемся с Вами в ближайшее время.<br><br>

{% if user.is_authenticated %}<p>Статус заказа можно отслеживать <a href="{% url 'order:detail' object.pk %}">здесь.</p></a>{% endif %}

</div>


{% endblock main_content  %}

src/orders/templates/orders/order_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title%} Редактирование заказа {% endblock title %}
{% block main_content %}
    <h1>Редактирование заказа</h1>
    <h5>{{cart.customer.first_name}}</h5>
    {% for book in cart.books.all %}{{book.book.name}} {{book.price}} руб. x{{book.quantity}}<br>{% endfor %}
    </p>   
    <h6>Итого: {{cart.total_summ}} руб. </h6>  
    <form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button align=center class="btn btn-success">Готово</button>
    </form>
{% endblock main_content  %}

src/orders/templates/orders/order_user_history.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title%} История заказов {% endblock title %}
{% block main_content %}
    <h2 class="row alert alert-warning">История заказов</h2>
    <form action="" method="GET">
    {{search_form|crispy}}
    </form>
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>       
<table class='table table-hover'>
<tr>
    <th>
    {% comment %} <a href="{% url 'order:history'%}?field=pk&direction={% if field_to_sort_on == 'pk' and direction_to_sort_on == 'up'  %}down{% else %}up{% endif %}"> {% endcomment %}
    #
    {% comment %} {% if field_to_sort_on == 'pk' and direction_to_sort_on == 'up' %} <i class="fas fa-chevron-up"></i> {% endcomment %}
    {% comment %} {% elif field_to_sort_on == 'pk' and direction_to_sort_on == 'down' %} <i class="fas fa-chevron-down"></i> {% endcomment %}
    {% comment %} {% endif %} {% endcomment %}
    {% comment %} </a> {% endcomment %}
    </th>
    <th>
    {% comment %} <a href="{% url 'order:history'%}?field=created&direction={% if field_to_sort_on == 'created' and direction_to_sort_on == 'up'  %}down{% else %}up{% endif %}"> {% endcomment %}
    Дата
    {% comment %} {% if field_to_sort_on == 'created' and direction_to_sort_on == 'up' %} <i class="fas fa-chevron-up"></i> {% endcomment %}
    {% comment %} {% elif field_to_sort_on == 'created' and direction_to_sort_on == 'down' %} <i class="fas fa-chevron-down"></i> {% endcomment %}
    {% comment %} {% endif %} {% endcomment %}
    {% comment %} </a> {% endcomment %}
    </th>
    <th>
    {% comment %} <a href="{% url 'order:history'%}?field=order_status&direction={% if field_to_sort_on == 'order_status' and direction_to_sort_on == 'up'  %}down{% else %}up{% endif %}"> {% endcomment %}
    Статус
    {% comment %} {% if field_to_sort_on == 'order_status' and direction_to_sort_on == 'up' %} <i class="fas fa-chevron-up"></i> {% endcomment %}
    {% comment %} {% elif field_to_sort_on == 'order_status' and direction_to_sort_on == 'down' %} <i class="fas fa-chevron-down"></i> {% endcomment %}
    {% comment %} {% endif %} {% endcomment %}
    {% comment %} </a> {% endcomment %}
    </th>
    <th>
    {% comment %} <a href="{% url 'order:history'%}?field=address&direction={% if field_to_sort_on == 'address' and direction_to_sort_on == 'up'  %}down{% else %}up{% endif %}"> {% endcomment %}
    Адрес
    {% comment %} {% if field_to_sort_on == 'address' and direction_to_sort_on == 'up' %} <i class="fas fa-chevron-up"></i> {% endcomment %}
    {% comment %} {% elif field_to_sort_on == 'address' and direction_to_sort_on == 'down' %} <i class="fas fa-chevron-down"></i> {% endcomment %}
    {% comment %} {% endif %} {% endcomment %}
    {% comment %} </a> {% endcomment %}
    </th>
    <th>Книги</th>
    <th>Итого,<br>руб.</th>
</tr>
    {% for order in object_list %}
    <tr>
        <td><a href = "{% url 'order:detail'  order.pk  %}">{{order.pk}}</a></td>
        <td>{{order.created}}</td>
        <td>{{order.order_status}}</td>
        <td>{{order.address}}</td>
        <td>{% for book in order.cart.books.all %}{{book.book.name}} x{{book.quantity}}<br>{% endfor %}</td>
        <td>{{order.cart.total_summ}}</td>
    </tr>
        {% endfor %}
</table>
{% endblock main_content  %}